### ISSUE TITLE
Sigmoid activation

### ISSUE THREAD

**Issue by krishnak** [zhen8838/K210_Yolo_framework#10]
In this line of [code](https://github.com/zhen8838/K210_Yolo_framework/blob/e5350c0166e1c9d9acb63166c31a17c514b31f04/yolo3_frame_test_public_maixpy/region_layer.c#L128) why 

`        activate_array(rl, index, 2 * rl->layer_width * rl->layer_height);`

Why is 2 used? shouldn't it be 4?  as there are 4 items in Co-ordinates.

Right now the sigmoid is applied only to 7x10x2 i.e first 140 elements and then the index shifts to 280 and applies for 70 elements.

Shouldn't it be 7x10x4 for applying to the coordinates? what is the logic behind this

**Comment by zhen8838** [comment]
only `x , y`  need sigmoid. `w , h` use log.

**Comment by krishnak** [comment]
thank you, do you know how to invoke the g++ compiler instead of gcc when building for K210? I am trying to include xtensor headers and I get an error
`
error: 'to_string' is not a member of 'std'`

**Comment by yeeshanqiao** [comment]
@zhen8838 , you said that only `x, y` need sigmoid activation, but what does these two lines of [code](https://github.com/zhen8838/K210_Yolo_framework/blob/e5350c0166e1c9d9acb63166c31a17c514b31f04/yolo3_frame_test_public_maixpy/region_layer.c#L129-L130) for? And I could not find the log op for `w, h`.
