### ISSUE TITLE
Project needs simple and natural optimizations

### ISSUE THREAD

**Issue by easy-and-simple** [zhen8838/K210_Yolo_framework#16]
This project needs following simple and basic optimizations
1. There is no any sense everyone to build train.txt and creating voc_img_ann.npy once more there is no directory xxxx as specified in example command: python3 make_voc_list.py xxxx/train.txt data/voc_img_ann.npy

2. There is no any sense all people to train model with over 3.2million parameters, so must be supplied
real pre-trained models with optimal accuracy

3. Must be added option for transfer learning in order to train custom classes

4. Code must be updated to tensorflow version 2 and latest versions of all other required components

**Comment by zhen8838** [comment]
1. The path of the dataset downloaded by each person is different, of course, `voc_img_ann.npy` must be regenerated

2. I am not an official of Kendryte, I am just a community enthusiast, this repo is just a demo.

3&4. I currently have other jobs, and I will not update this repo specifically.

**Comment by easy-and-simple** [comment]
If path to dataset is different this is because you didn't specified in your instructions where to download it, and voc_img_ann.npy can't be generated because make_voc_list.py is not working, so you project is useless if you didn't implement optimizations I suggested. 
1. There is no way dataset path to be different for different people because it is relative and not absolute
2. Because you don't want to make your project working we need to rewrite all files in your project right? Of course it is more simple to us to debug and rewrite all code instead to move dataset in correct directory right?!
Your code is  not working and your repo is useless because you didn't make these simple and natural steps I suggested. 

 make_voc_list.py is just first file from your project that we need to use and it is not working. I am sure that other files will not work too. If you don't want to update repo then you can delete it right now as completely useless and just taking space on guthub

Traceback (most recent call last):
  File "make_voc_list.py", line 38, in <module>
    main(args.train_file, args.output_file)
  File "make_voc_list.py", line 19, in main
    lines = np.array([
  File "make_voc_list.py", line 23, in <listcomp>
    np.array(skimage.io.imread(image_path_list[i]).shape[0:2])]
AttributeError: module 'skimage' has no attribute 'io'

**Comment by easy-and-simple** [comment]
I don't know what is your problem but you have made everything possible to make this repository not working
file name don't match, modules don't exist, weight full or tiny can't be loaded, no explanation for anything
nothing works
Did you ever tried to load weights? Layer count not match and script returns error and exit

**Comment by easy-and-simple** [comment]
I wasted 1 day to found out that trained models are too big to be loaded in maixpy
4.6MB RAM and KPU RAM is at the edge
really useless repo
I will look for normal repo made by someone that knows how to make working projects and is friendly to people
I checked and your replays in Chinese language to see how you communicate you chinese guys, and what a surprise same useless replays. Guy is telling you that he is new and need help, and you say him - write your own script, make database and train
You are really evil
Obviously you have stolen repo form someone else, then changed names of files and modules to make it not working, uploaded so called pre-trained models with zeroed weights and some useless weights not matching these models that can't be loaded without modifying python scripts code
Despite of your effort to make repo not working and useless I was able to run and train models wasting 1 day of my life just to found out that trained models are giant and cant be loaded by maixpy

You know where to put to yourself this right?
 Easy to use with other datasets
 Support multiple model backbones and expand more
 Support n number of output layers and m anchors
 Support model weight pruning
 Portable model to kendryte K210 chip
