### ISSUE TITLE
自己的数据集

### ISSUE THREAD

**Issue by vseasky** [zhen8838/K210_Yolo_framework#19]
![image](https://user-images.githubusercontent.com/47177625/86906661-73a0a200-c146-11ea-8a04-1f8588a64421.png)
正常导出img_ann.npy，没有成功导出过anchor.npy，仅voc可以正常导出

**Comment by zhen8838** [comment]
通过参数`LOW`与`HIGH`控制`anchor`的初始化范围防止出现`nan`

**Comment by vseasky** [comment]
OK,谢啦
