### ISSUE TITLE
Can't produce model with only 1 output layer because code raises error and exits

### ISSUE THREAD

**Issue by easy-and-simple** [zhen8838/K210_Yolo_framework#23]
K210\K210_Yolo_framework\tools\utils.py", line 545, in tf_xywh_to_all
    all_pred_xy = (tf.sigmoid(grid_pred_xy[..., :]) + h.xy_offset[layer]) / h.out_hw[layer][::-1]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by zhen8838** [comment]
Because I did not define a single output model,so you need to modify yolo model code, 
eg. [this](https://github.com/zhen8838/K210_Yolo_framework/blob/e5350c0166e1c9d9acb63166c31a17c514b31f04/models/yolonet.py#L40)
```python
    y2 = compose(
        keras.layers.Concatenate(),
        DarknetConv2D_BN_Leaky(128, (3, 3)),
        DarknetConv2D(anchor_num * (class_num + 5), (1, 1)))([x2, x1])

    y1_reshape = Reshape((7, 10, anchor_num, 5 + class_num), name='l1')(y1)
    y2_reshape = Reshape((14, 20, anchor_num, 5 + class_num), name='l2')(y2)

    yolo_model = keras.Model(inputs, [y1, y2])
    yolo_model_warpper = keras.Model(inputs, [y1_reshape, y2_reshape])

    return yolo_model, yolo_model_warpper
```

**Comment by easy-and-simple** [comment]
OK. Thank you!
Now it is working
