### ISSUE TITLE
「Solved」README中Freeze的不是Prune Model产生的model？

### ISSUE THREAD

**Issue by BackMountainDevil** [zhen8838/K210_Yolo_framework#47]
```bash
# Prune Model

make train MODEL=xxxx MAXEP=1 ILR=0.0003 DATASET=voc CLSNUM=20 BATCH=16 PRUNE=True CKPT=log/xxxxxx/yolo_model.h5 END_EPOCH=1

# When training finish, will save model as log/xxxxxx/yolo_prune_model.h5.
# Freeze
toco --output_file mobile_yolo.tflite --keras_model_file log/xxxxxx/yolo_model.h5
```

修剪之后的是  log/xxxxxx/yolo_prune_model.h5. 冻结的不应该是修建出来的模型吗？为啥还是修建之前的训练模型呢？-> log/xxxxxx/yolo_model.h5

**Comment by zhen8838** [comment]
因为裁剪之后的模型只是更加稀疏了，但对于k210来说并没有稀疏加速的功能，因此还是选择导出原始模型保证精度。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Kearney ***@***.***&gt;
发送时间: 2022年3月18日 10:08
收件人: zhen8838/K210_Yolo_framework ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zhen8838/K210_Yolo_framework] README中Freeze的不是Prune Model产生的model？ (Issue #47)





 # Prune Model make train MODEL=xxxx MAXEP=1 ILR=0.0003 DATASET=voc CLSNUM=20 BATCH=16 PRUNE=True CKPT=log/xxxxxx/yolo_model.h5 END_EPOCH=1 # When training finish, will save model as log/xxxxxx/yolo_prune_model.h5. # Freeze toco --output_file mobile_yolo.tflite --keras_model_file log/xxxxxx/yolo_model.h5
 
修剪之后的是  log/xxxxxx/yolo_prune_model.h5. 冻结的不应该是修建出来的模型吗？为啥还是修建之前的训练模型呢？-&gt; log/xxxxxx/yolo_model.h5
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BackMountainDevil** [comment]
原来如此，我还以为是大家都小手一抖写错了，没想到原来是这个原因，听君一席话，胜读十年书。感谢亲百忙之中予以解答
