### ISSUE TITLE
How to infer a folder of images?

### ISSUE THREAD

**Issue by lisenjie757** [zhen8838/K210_Yolo_framework#53]
As the title

**Comment by zhen8838** [comment]
sorry, not support batch inference. You need add loop while in the keras_infer.py


发自我的iPhone

------------------ Original ------------------
From: lisenjie757 ***@***.***&gt;
Date: 周三,4月 20,2022 17:08
To: zhen8838/K210_Yolo_framework ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhen8838/K210_Yolo_framework] How to infer a folder of images?(Issue #53)





 
As the title

**Comment by lisenjie757** [comment]
thank you, i add a loop in the keras_infer.py, it can work.
